"""create application schema

Revision ID: ef160622e343
Revises: 20260929_0001
Create Date: 2026-09-29 15:24:38.530601
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ef160622e343'
down_revision: Union[str, Sequence[str], None] = '20260929_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.String(length=128), nullable=False),
    sa.Column('wpdx_id', sa.String(length=128), nullable=False),
    sa.Column('row_id_export', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('survey_year', sa.Integer(), nullable=True),
    sa.Column('survey_month', sa.Integer(), nullable=True),
    sa.Column('source_dataset_title', sa.Text(), nullable=True),
    sa.Column('source_org', sa.Text(), nullable=True),
    sa.Column('observed_status', sa.Text(), nullable=True),
    sa.Column('observed_status_id', sa.String(length=32), nullable=True),
    sa.Column('status_raw_text', sa.Text(), nullable=True),
    sa.Column('label_functional_status', sa.Float(), nullable=True),
    sa.Column('label_functional_status_id', sa.Integer(), nullable=True),
    sa.Column('water_source', sa.Text(), nullable=True),
    sa.Column('water_technology', sa.Text(), nullable=True),
    sa.Column('water_tech_category', sa.Text(), nullable=True),
    sa.Column('management_type', sa.Text(), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('installer', sa.Text(), nullable=True),
    sa.Column('install_year', sa.Integer(), nullable=True),
    sa.Column('age_at_survey_years', sa.Float(), nullable=True),
    sa.Column('usage_capacity', sa.Float(), nullable=True),
    sa.Column('subjective_water_quality', sa.Text(), nullable=True),
    sa.Column('inside_tz_adm0', sa.Boolean(), nullable=True),
    sa.Column('dist_to_tz_border_m', sa.Float(), nullable=True),
    sa.Column('nbs_region', sa.Text(), nullable=True),
    sa.Column('nbs_district', sa.Text(), nullable=True),
    sa.Column('nbs_ward', sa.Text(), nullable=True),
    sa.Column('nbs_ward_code', sa.String(length=64), nullable=True),
    sa.Column('wpdx_adm1_region', sa.Text(), nullable=True),
    sa.Column('wpdx_adm2_district', sa.Text(), nullable=True),
    sa.Column('wpdx_region_matches_nbs', sa.Boolean(), nullable=True),
    sa.Column('wpdx_is_urban', sa.Boolean(), nullable=True),
    sa.Column('dist_nearest_any_water_point_m', sa.Float(), nullable=True),
    sa.Column('n_water_points_within_500m', sa.Integer(), nullable=True),
    sa.Column('n_water_points_within_1000m', sa.Integer(), nullable=True),
    sa.Column('n_water_points_within_5000m', sa.Integer(), nullable=True),
    sa.Column('wpdx_is_duplicate_flag', sa.Boolean(), nullable=True),
    sa.Column('n_history_observations', sa.Integer(), nullable=True),
    sa.Column('wpdx_dist_primary_road_m', sa.Float(), nullable=True),
    sa.Column('wpdx_dist_secondary_road_m', sa.Float(), nullable=True),
    sa.Column('wpdx_dist_tertiary_road_m', sa.Float(), nullable=True),
    sa.Column('wpdx_dist_city_m', sa.Float(), nullable=True),
    sa.Column('wpdx_dist_town_m', sa.Float(), nullable=True),
    sa.Column('wpdx_local_population_1km', sa.Float(), nullable=True),
    sa.Column('wpdx_water_point_population_leaky', sa.Float(), nullable=True),
    sa.Column('wpdx_crucialness_score_leaky', sa.Float(), nullable=True),
    sa.Column('wpdx_pressure_score_leaky', sa.Float(), nullable=True),
    sa.Column('wpdx_rehab_priority_leaky', sa.Float(), nullable=True),
    sa.Column('wpdx_pop_would_gain_access_leaky', sa.Float(), nullable=True),
    sa.Column('dist_nearest_functional_other_m_leaky', sa.Float(), nullable=True),
    sa.Column('rain_3m_prior_mm', sa.Float(), nullable=True),
    sa.Column('rain_3m_pct_of_normal', sa.Float(), nullable=True),
    sa.Column('rain_3m_z', sa.Float(), nullable=True),
    sa.Column('rain_6m_prior_mm', sa.Float(), nullable=True),
    sa.Column('rain_6m_pct_of_normal', sa.Float(), nullable=True),
    sa.Column('rain_6m_z', sa.Float(), nullable=True),
    sa.Column('rain_12m_prior_mm', sa.Float(), nullable=True),
    sa.Column('rain_12m_pct_of_normal', sa.Float(), nullable=True),
    sa.Column('rain_12m_z', sa.Float(), nullable=True),
    sa.Column('rain_mean_annual_1991_2020_mm', sa.Float(), nullable=True),
    sa.Column('dry_months_prior12_lt30mm', sa.Float(), nullable=True),
    sa.Column('rain_features_available', sa.Boolean(), nullable=True),
    sa.Column('worldpop2022_pop_within_500m', sa.Float(), nullable=True),
    sa.Column('worldpop2022_pop_within_1000m', sa.Float(), nullable=True),
    sa.Column('worldpop2022_pop_within_2000m', sa.Float(), nullable=True),
    sa.Column('worldpop2022_density_per_km2_1km', sa.Float(), nullable=True),
    sa.Column('dist_nearest_health_facility_m', sa.Float(), nullable=True),
    sa.Column('dist_nearest_school_m', sa.Float(), nullable=True),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='ck_water_points_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_water_points_longitude'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', name='uq_water_points_master_id'),
    sa.UniqueConstraint('row_id_export', name='uq_water_points_row_id_export'),
    sa.UniqueConstraint('wpdx_id', name='uq_water_points_wpdx_id')
    )
    op.create_index('ix_water_points_map_coordinates', 'water_points', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_water_points_nbs_region', 'water_points', ['nbs_region'], unique=False)
    op.create_index('ix_water_points_observed_status', 'water_points', ['observed_status'], unique=False)
    op.create_table('consequence_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_point_id', sa.Integer(), nullable=False),
    sa.Column('risk_available', sa.Boolean(), nullable=False),
    sa.Column('probability_non_functional', sa.Float(), nullable=True),
    sa.Column('probability_functional', sa.Float(), nullable=True),
    sa.Column('predicted_status', sa.String(length=64), nullable=True),
    sa.Column('decision_threshold', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(length=32), nullable=True),
    sa.Column('risk_band_note', sa.Text(), nullable=True),
    sa.Column('prediction_methodology_version', sa.String(length=64), nullable=True),
    sa.Column('impact_available', sa.Boolean(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('impact_methodology_version', sa.String(length=64), nullable=True),
    sa.Column('population_component', sa.Float(), nullable=True),
    sa.Column('alternative_scarcity_component', sa.Float(), nullable=True),
    sa.Column('risk_impact_index_available', sa.Boolean(), nullable=False),
    sa.Column('risk_impact_index', sa.Float(), nullable=True),
    sa.Column('risk_impact_index_note', sa.Text(), nullable=True),
    sa.Column('consequence_priority_methodology_version', sa.String(length=64), nullable=False),
    sa.Column('consequence_priority_unavailable_reason', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['water_point_id'], ['water_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consequence_results_risk_impact_index', 'consequence_results', ['risk_impact_index'], unique=False)
    op.create_table('impact_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_point_id', sa.Integer(), nullable=False),
    sa.Column('impact_available', sa.Boolean(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('population_component', sa.Float(), nullable=True),
    sa.Column('alternative_scarcity_component', sa.Float(), nullable=True),
    sa.Column('impact_unavailable_reason', sa.Text(), nullable=True),
    sa.Column('impact_methodology_version', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['water_point_id'], ['water_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_impact_results_impact_score', 'impact_results', ['impact_score'], unique=False)
    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_point_id', sa.Integer(), nullable=False),
    sa.Column('probability_non_functional', sa.Float(), nullable=True),
    sa.Column('probability_functional', sa.Float(), nullable=True),
    sa.Column('predicted_status', sa.String(length=64), nullable=True),
    sa.Column('decision_threshold', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(length=32), nullable=True),
    sa.Column('risk_band_note', sa.Text(), nullable=True),
    sa.Column('prediction_methodology_version', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('decision_threshold IS NULL OR decision_threshold BETWEEN 0 AND 1', name='ck_prediction_decision_threshold'),
    sa.CheckConstraint('probability_functional IS NULL OR probability_functional BETWEEN 0 AND 1', name='ck_prediction_functional_probability'),
    sa.CheckConstraint('probability_non_functional IS NULL OR probability_non_functional BETWEEN 0 AND 1', name='ck_prediction_nonfunctional_probability'),
    sa.ForeignKeyConstraint(['water_point_id'], ['water_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_results_predicted_status', 'prediction_results', ['predicted_status'], unique=False)
    op.create_index('ix_prediction_results_probability_non_functional', 'prediction_results', ['probability_non_functional'], unique=False)
    op.create_index('ix_prediction_results_risk_band', 'prediction_results', ['risk_band'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prediction_results_risk_band', table_name='prediction_results')
    op.drop_index('ix_prediction_results_probability_non_functional', table_name='prediction_results')
    op.drop_index('ix_prediction_results_predicted_status', table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index('ix_impact_results_impact_score', table_name='impact_results')
    op.drop_table('impact_results')
    op.drop_index('ix_consequence_results_risk_impact_index', table_name='consequence_results')
    op.drop_table('consequence_results')
    op.drop_index('ix_water_points_observed_status', table_name='water_points')
    op.drop_index('ix_water_points_nbs_region', table_name='water_points')
    op.drop_index('ix_water_points_map_coordinates', table_name='water_points')
    op.drop_table('water_points')
    # ### end Alembic commands ###

